### PR TITLE
Fix an issue preventing #to_s from including the version for subspecs

### PR DESCRIPTION
**Pull request by amorde**
Fixes a regression caused by #555

### CODE REVIEW

**Comment by amorde** [comment]
Fixed Rubocop

**Comment by dnkoutso** [comment]
Doesnt look like its happy still

**Comment by dnkoutso** [comment]
@amorde ran Rubocop for you, should be fixed now and will merge on green.

**Comment by amorde** [comment]
Thanks! Not sure what happened there

**Pull request merged**
