### PR TITLE
[JSON] Serialize default platforms when converting to JSON

### LINKED ISSUE #267: Include default platforms when serializing podspec

### PR DESCRIPTION
**Pull request by segiddins**
Closes #267. 

- [x] CHANGELOG

\c @alloy @neonichu @orta

### CODE REVIEW

**Comment by alloy** [comment]
Neither tickets explain why this is needed, can you include that?

**Comment by orta** [comment]
I think it's to make it obvious when pushing to trunk what platforms are supported, this will lock the platforms to what you knew of at the time of publishing. E.g. No tvOS last year

**Comment by segiddins** [comment]
This makes it so when a new platform comes out, the spec won't pretend to support it when it was never actually linted for that platform.

**Comment by alloy** [comment]
@segiddins Perfect, thanks for clarifying. Looks good to me :+1:

**Comment by neonichu** [comment]
LGTM :+1:

**Pull request merged**
