### PR TITLE
 handle http/302 like 301 during download_and_save_with_retries_asynch

### PR DESCRIPTION
**Pull request by kessit**
adding to 1-10-stable branch to allow for adding the change to 1.10.2

### CODE REVIEW

**Comment by kessit** [comment]
this issue is crippling our CI setup, so would be greatly appreciated if a 1.10.2 could be created with this fix included...

**Comment by igor-makarov** [comment]
We can't really commit to a release schedule, due to being volunteer based. It's best if you used the `master` branch gem if it's urgent.

**Review by AaronWashington — APPROVED** [review]

**Comment by dnkoutso** [comment]
@igor-makarov do you approve this change? if so I can merge for 1.10.2.

**Comment by dnkoutso** [comment]
Probably a changelog entry is a good idea.

**Review by igor-makarov — APPROVED** [review]

**Comment by igor-makarov** [comment]
@dnkoutso yeah, this is a backport of a change we already have in main.

**Comment by dnkoutso** [comment]
ah perfect!

**Pull request merged**
