### PR TITLE
Lazy require Typhoeus because its load takes 300ms

### PR DESCRIPTION
**Pull request by igor-makarov**
Also https://github.com/CocoaPods/CocoaPods/pull/9447

### CODE REVIEW

**Comment by igor-makarov** [comment]
Rebased on `master`.

**Comment by igor-makarov** [comment]
CI is failing because of https://github.com/CocoaPods/Core/pull/609

**Comment by dnkoutso** [comment]
@igor-makarov can you rebase?

**Comment by igor-makarov** [comment]
@dnkoutso done!

**Pull request merged**
