### PR TITLE
[YAMLHelper] Fix the serialization of strings that have weird characters...

### PR DESCRIPTION
**Pull request by segiddins**
.../patterns

Closes https://github.com/CocoaPods/Core/issues/213.
Closes https://github.com/CocoaPods/CocoaPods/issues/2837.

\c @kylef @alloy @floere

### CODE REVIEW

**Comment by kylef** [comment]
Nice, can you add a test to ensure that 1.2 as a Float is still a YAML number too?

**Comment by segiddins** [comment]
Our serializer doesn't handle numbers

-Samuel E. Giddins

On Mar 8, 2015, at 5:12 AM, Kyle Fuller <notifications@github.com> wrote:

Nice, can you add a test to ensure that 1.2 as a Float is still a YAML number too?

**Comment by floere** [comment]
@segiddins From the test alone it's hard to glean what the point of this is - help?

**Comment by floere** [comment]
(Mostly confused by the --- replacement)

**Comment by segiddins** [comment]
Ah. It uses Psych to ensure that we properly serialize strings, such as '1.2', which, if unquoted, appears as a FixNum.

**Comment by floere** [comment]
Thanks, I see – we want to return only the YAMLified value, not a YAML document. Should the `.` be escaped? (`\.`)

**Comment by segiddins** [comment]
> Thanks, I see – we want to return only the YAMLified value, not a YAML document.

Exactly, and the YAML module has no method that does that.

**Comment by segiddins** [comment]
Let's merge this @kylef :smiling_imp:

**Pull request merged**
