### PR TITLE
[DSLError] Do not show update suggestion on argument errors

### PR DESCRIPTION
**Pull request by manuyavuz**
We should not show the update suggestion on argument errors.

### CODE REVIEW

**Comment by manuyavuz** [comment]
@segiddins This change caused the full crash log to be printed instead of pretty information message. What could cause this, is initialize method an overridden one? Here is the sample stack trace:

```
ArgumentError - Got `"true"`, should be a boolean
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile/target_definition.rb:329:in `set_inhibit_warnings_for_pod'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile/target_definition.rb:780:in `parse_inhibit_warnings'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile/target_definition.rb:493:in `store_pod'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile/dsl.rb:194:in `pod'
/Users/manuyavuz/Development/Netmera/Netmera/Example/Podfile:8:in `default_pods'
/Users/manuyavuz/Development/Netmera/Netmera/Example/Podfile:19:in `block (2 levels) in from_ruby'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile/dsl.rb:294:in `target'
/Users/manuyavuz/Development/Netmera/Netmera/Example/Podfile:18:in `block in from_ruby'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile.rb:291:in `eval'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile.rb:291:in `block in from_ruby'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile.rb:287:in `new'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile.rb:287:in `from_ruby'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/Core/lib/cocoapods-core/podfile.rb:253:in `from_file'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/CocoaPods/lib/cocoapods/config.rb:189:in `podfile'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/CocoaPods/lib/cocoapods/command.rb:112:in `verify_podfile_exists!'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/CocoaPods/lib/cocoapods/command/project.rb:96:in `run'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/CLAide/lib/claide/command.rb:312:in `run'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/CocoaPods/lib/cocoapods/command.rb:48:in `run'
/Users/manuyavuz/Development/OpenSource/Cocoapods/Rainforest/CocoaPods/bin/pod:44:in `<main>'
```

**Comment by segiddins** [comment]
Are you running in development mode? (`COCOA_PODS_ENV=development`)

**Comment by segiddins** [comment]
@manuyavuz should be fixed now

**Comment by manuyavuz** [comment]
@CocoaPods/core can somebody review this?

**Comment by k0nserv** [comment]
LGTM

**Comment by segiddins** [comment]
👍🏻

**Pull request merged**
