### PR TITLE
[Version] Compare differently for sorting and equality

### PR DESCRIPTION
**Pull request by segiddins**
Closes CocoaPods/CocoaPods#4365.

\c @floere

### CODE REVIEW

**Comment by floere** [comment]
:banana: :+1:

**Comment by segiddins** [comment]
I am kinda nervous about breaking trichotomy, though.

**Comment by floere** [comment]
@segiddins How many tests would we have to write to cover all cases? ("all" as in – not testing all Integers)

**Comment by segiddins** [comment]
@floere I'm not sure what you're asking?

**Pull request merged**
