### PR TITLE
Support using macos as an alias for osx

### PR DESCRIPTION
**Pull request by segiddins**
- [x] Specs
- [x] CHANGELOG

### CODE REVIEW

**Comment by manuyavuz** [comment]
Fast!

**Comment by segiddins** [comment]
This should pass now if anyone wants to finish it up

**Comment by dnkoutso** [comment]
@segiddins whats remaining here besides a rebase? Tests?

**Comment by segiddins** [comment]
I don't know, definitely a changelog and maybe more tests?

**Comment by segiddins** [comment]
Changelog added, a year later

**Comment by dnkoutso** [comment]
Will need a rebase, unless its not yet 100% done.

**Comment by segiddins** [comment]
Rebased

**Comment by dnkoutso** [comment]
celebration!

**Pull request merged**
