### PR TITLE
Don't assume all responses have headers

### PR DESCRIPTION
**Pull request by amorde**

### CODE REVIEW

**Comment by dnkoutso** [comment]
Is this a 1.9 fix? If so we can target the `1-9-stable` branch.

**Comment by amorde** [comment]
Ah yeah, can do

**Comment by amorde** [comment]
Tests won't pass until #609 is merged or something else fixes the tests

**Comment by dnkoutso** [comment]
Should we add a changelog entry? I.e is this a bug fix?

**Comment by amorde** [comment]
yes, good catch

**Comment by dnkoutso** [comment]
@amorde can you rebase for 1-9-stable since CI is fixed? I will merge and ship for 1.9.0.beta.3.

**Comment by amorde** [comment]
Yep can do

**Comment by dnkoutso** [comment]
@amorde just rubcopster failing

**Pull request merged**
