### PR TITLE
List the platforms in the platform docstring

### PR DESCRIPTION
**Pull request by pepasflo**
Hello,

This PR is a follow-up to issue https://github.com/CocoaPods/CocoaPods/issues/8541

Thanks!

### CODE REVIEW

**Comment by dnkoutso** [comment]
If your goal is for this change to appear here https://guides.cocoapods.org/syntax/podspec.html#platform then what you have here will not. You can add more @example entries which would end up in the guides.

**Comment by amorde** [comment]
You could also add a comment to one of the existing examples listing the possible options

**Comment by dnkoutso** [comment]
@pepasflo can you rebase please?

**Comment by dnkoutso** [comment]
ping @pepasflo

**Comment by dnkoutso** [comment]
last ping @pepasflo

**Pull request closed without merging**
