### PR TITLE
Allow duplicate dependencies when they have no conflict

### PR DESCRIPTION
**Pull request by Whirlwind**
see https://github.com/CocoaPods/CocoaPods/pull/7999

### CODE REVIEW

**Comment by Whirlwind** [comment]
The Ruby 2.3.4 seems that have some problem.

**Comment by dnkoutso** [comment]
@Whirlwind want to rebase and update this PR?

**Comment by Whirlwind** [comment]
@dnkoutso Do you agree with my idea? If yes, I will update this PR.

**Comment by dnkoutso** [comment]
@Whirlwind I do not think this will be implemented currently. I am going to close the PR as it has been lingering for a while. I suggest we also close #7999.

**Pull request closed without merging**
