### PR TITLE
Updates inherited target quote style

### PR DESCRIPTION
**Pull request by ashfurrow**
I saw this [on the guides](https://guides.cocoapods.org/syntax/podfile.html) so I opened a PR.

screen shot 2019-01-04 at 5 04 09 pm

### CODE REVIEW

**Comment by ashfurrow** [comment]
Can we merge this PR? Or do we need to wait to fix CI first?

**Comment by amorde** [comment]
I don't have the ability to merge it without CI, @segiddins might

**Comment by dnkoutso** [comment]
@ashfurrow rebasing will fix CI.

**Comment by ashfurrow** [comment]
It sure did!

**Pull request merged**
