### PR TITLE
Remove the equals sign from the spec.dependency command

### PR DESCRIPTION
**Pull request by kubatru**

### CODE REVIEW

**Comment by orta** [comment]
Awesome! Any chance you can make it just one space between them 💃? Then this is good to go - thanks @kubatru

**Comment by kubatru** [comment]
No problem, just added second commit. Did not mention the space reduction in the description, if it is ok.

**Comment by segiddins** [comment]
👍 thanks!

**Comment by kubatru** [comment]
I thank you guys.

**Pull request merged**
