### PR TITLE
[DSLError] Present fancy error messages even for things like SyntaxErrors that dont have cooperative backtraces

### PR DESCRIPTION
**Pull request by segiddins**
The new functionality is demonstrated at https://github.com/CocoaPods/Core/pull/226/files#diff-7dd13ddd3ab90c5487ed0e20928c423eR33

\c @kylef @orta

### CODE REVIEW

**Comment by orta** [comment]
Oh I see, this is for when you're writing a pod? Looks much better :dancers:

**Comment by segiddins** [comment]
(This work was inspired by getting https://github.com/bundler/bundler/pull/3480 to work).

**Comment by kylef** [comment]
Looks good, let's not merge this until 0.36.1 is out.

**Comment by segiddins** [comment]
0.36.1 is out, can we merge?

**Comment by kylef** [comment]
Certainly, can we get a CHANGELOG entry too?

**Comment by segiddins** [comment]
CHANGELOG entry added.

**Pull request merged**
