### PR TITLE
use CDN source in example

### PR DESCRIPTION
**Pull request by shifujun**
For page:
https://guides.cocoapods.org/syntax/podfile.html#source

### CODE REVIEW

**Review by paulb777 — APPROVED** [review]
Nice cleanup. thanks!

**Comment by bradfol** [comment]
I was just about to make a PR with the same change 👍

**Review by dnkoutso — APPROVED** [review]

**Comment by shifujun** [comment]
> I think there is also one more old reference on this page https://guides.cocoapods.org/using/the-podfile.html
> 
> Does anyone know which repo file backs that page?

here!

image

https://github.com/CocoaPods/guides.cocoapods.org/blob/master/source/using/the-podfile.html.md

**Comment by bradfol** [comment]
@shifujun thanks! PR here https://github.com/CocoaPods/guides.cocoapods.org/pull/213

**Pull request merged**
