### PR TITLE
For fix slow dependency issue(base on 1.0.0).

### PR DESCRIPTION
**Pull request by yanzhiwei147**
For master issue [#5180](https://github.com/CocoaPods/CocoaPods/issues/5180)

### CODE REVIEW

**Comment by segiddins** [comment]
This needs to reset the hash value when changing the name or version

**Comment by yanzhiwei147** [comment]
@segiddins So the name or version may be changed? It's mutable?

**Comment by segiddins** [comment]
@yanzhiwei147 yes

**Comment by yanzhiwei147** [comment]
@segiddins It can i add two `attr_accessor` for `name` and `version`?

**Comment by segiddins** [comment]
I'm sorry, I don't understand the question

**Comment by yanzhiwei147** [comment]
@segiddins Sorry, the mean is how to reset the hash value when changing the name or version.

**Comment by segiddins** [comment]
Overwrite the `name=` and `version=` methods, making sure to set the cached hash value back to nil. This will also require test coverage

**Comment by jafara** [comment]
@yanzhiwei147 you planning on finishing this PR?

**Comment by yanzhiwei147** [comment]
@jafara Yes. When I have time ,I will push the change.

**Comment by jafara** [comment]
yo @yanzhiwei147 , you gonna finish this or what?

**Comment by orta** [comment]
That's not very polite @jafara - if you wanted to speed this up, _you_ can create a new PR addressing the feedback

**Comment by dnkoutso** [comment]
I can possibly jump in and wrap this up. I manually applied the fix and it dropped our `pod install` time from ~47seconds to ~41 seconds, not a bad improvement!

**Comment by dnkoutso** [comment]
I believe this can be closed now :)

**Pull request closed without merging**
