### PR TITLE
[YAMLHelper] Ensure the YAML doesnt have preceding >-

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/CocoaPods/CocoaPods/issues/4740.

\c @floere

### CODE REVIEW

**Comment by segiddins** [comment]
merging since this got no comments

**Comment by floere** [comment]
@segiddins An short explanation would help in getting comments.

**Comment by segiddins** [comment]
@floere it fixes the linked-to issue -- psych 2.0.11 would put strings dumped with a max line-width of `-1` inside a `>-` node, breaking our serialization of string keys

**Comment by floere** [comment]
@segiddins Thanks! :bow:

**Comment by orta** [comment]
awesome!

**Pull request merged**
