### PR TITLE
Added work with netrc file to perform autologin if CDN repo requires basic auth

### PR DESCRIPTION
**Pull request by igorudovika**
Fix  for https://github.com/CocoaPods/CocoaPods/issues/9151 issue

### CODE REVIEW

**Comment by dnkoutso** [comment]
cc @igor-makarov want to take a stab at reviewing this?

**Comment by igor-makarov** [comment]
I'm thinking that #580 would allow for a much more straightforward implementation, as cURL and Typhoeus (which wraps it) support `.netrc` out of the box.

**Comment by igorudovika** [comment]
> cURL
I have done few tests with Typhoeus. Unfortunately it does not work. Seems credentials from .netrc is taken into request only for command line `curl` version. Same true for .curlrc

**Comment by igor-makarov** [comment]
Did yoy check this option out?
https://github.com/typhoeus/ethon/blob/cf1d26158755de7a536ac8da3d344ae567bea719/lib/ethon/curls/options.rb#L305

**Comment by igorudovika** [comment]
> Did you check this option out?
> https://github.com/typhoeus/ethon/blob/cf1d26158755de7a536ac8da3d344ae567bea719/lib/ethon/curls/options.rb#L305

nope, let me check

**Comment by igorudovika** [comment]
> > Did you check this option out?
> > https://github.com/typhoeus/ethon/blob/cf1d26158755de7a536ac8da3d344ae567bea719/lib/ethon/curls/options.rb#L305
> 
> nope, let me check

yep, with such option it works. Ok then I will wait #580 merge and update PR after

**Pull request closed without merging**
