### PR TITLE
[Podfile] Sub out smart quotes

### PR DESCRIPTION
**Pull request by segiddins**
how terrible of an idea is this?

\c @neonichu @alloy @indirect

### CODE REVIEW

**Comment by neonichu** [comment]
:+1:

**Comment by alloy** [comment]
Seems smart :+1: (pun!)

Maybe also log a warning, though? As there might be other encoding issues? Although I can't think of any right now :smile:

**Comment by neonichu** [comment]
I think the warning would make sense, maybe specifically mentioning the most likely situation, the user using TextEdit, so that they can avoid it in the future.

We should also have some specs and a changelog ;)

**Comment by indirect** [comment]
Mostly I'm just mad I didn't think of this sooner. Can you implement this for Bundler? :raised_hands: :bow:

**Comment by segiddins** [comment]
@neonichu agree with those suggestions, since this could definitely go wrong

**Comment by k0nserv** [comment]
I am pretty sure it's not only TextEdit, we had this issue in slack and as it turns out this behaviour is configurable in OSX by right clicking certain input fields. 

Here's how it looks in slack
![screen shot 2015-06-21 at 13 58 34]
(https://cloud.githubusercontent.com/assets/1333960/8271539/aa589b54-181d-11e5-91db-05f1ccc8dc6d.png)

**Comment by neonichu** [comment]
@k0nserv you're right, but all the programmery text editors don't do it **and** TextEdit is the default application for editing Podfiles, even if other editors are installed, because it has no file extension. IMO, it's better to be wrong in an unlikely case than overcomplicating the message for many.

**Comment by k0nserv** [comment]
@neonichu Sounds reasonable, but adding an extra note for the case that one does not use TextEdit wouldn't complicate things much IMO.

> pod install
[!] Your Podfile has been sanitised from smart quotes.
To avoid such issues in the future, you should not use TextEdit for editing it.
If you are not using TextEdit turn of smart quotes in your editor

This will catch both cases and users of TextEdit will stop when they see it mentioned

**Comment by neonichu** [comment]
@k0nserv true, yours is better :+1:

**Comment by segiddins** [comment]
Warning added

**Comment by k0nserv** [comment]
:+1:

**Pull request merged**
